# Generated by Django 5.0.2 on 2024-02-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_datafile_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='original_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
    ]
