# Generated by Django 5.0.2 on 2024-02-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_datafile_original_name_datafile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['date']},
        ),
    ]
