# Generated by Django 5.0.2 on 2024-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_data_source_alter_data_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('superseded', 'Superseded'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
