# Generated by Django 5.0.2 on 2024-03-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_datafile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='website.datafile'),
        ),
    ]
