# Generated by Django 5.0.2 on 2024-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
