# Generated by Django 5.0.2 on 2024-03-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_datadescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadescription',
            options={'ordering': ['activity__name']},
        ),
        migrations.AlterModelTable(
            name='datadescription',
            table='data_descriptions',
        ),
    ]
