# Generated by Django 5.0.2 on 2024-03-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_datadescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'indicators',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.indicator')),
            ],
            options={
                'db_table': 'indicator_descriptions',
                'ordering': ['indicator', 'rating'],
            },
        ),
    ]
