# Generated by Django 5.0.2 on 2024-03-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_indicator_indicatordescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordescription',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='website.indicator'),
        ),
        migrations.CreateModel(
            name='DataQualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='website.datadescription')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.indicatordescription')),
            ],
            options={
                'db_table': 'data_quality_indicators',
                'ordering': ['indicator_id', 'indicator__rating'],
            },
        ),
    ]
