# Generated by Django 5.0.2 on 2024-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_indicatordescription_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordescription',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
