# Generated by Django 5.0.2 on 2024-03-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_indicatordescription_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatordescription',
            name='color',
        ),
    ]
