# Generated by Django 5.0.2 on 2024-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_indicatordescription_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='emissions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of GHG emissions per kilogram (Kg of CO2 equivalent)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='land_use',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of Land use per kilogram (m3)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='water_use',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of Freshwater withdrawals per kilogram (liters)', max_digits=6, null=True),
        ),
    ]
