# Generated by Django 5.0.2 on 2024-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_foodgroup_emissions_foodgroup_land_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='notes_methodology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
