# Generated by Django 5.0.2 on 2024-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_foodgroup_notes_methodology'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='ideal_consumption',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ideal per capita consumption (g/day)', null=True),
        ),
    ]
