# Generated by Django 5.0.2 on 2024-04-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_idealconsumption_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='is_human_food',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
