# Generated by Django 5.0.2 on 2024-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_city_shortname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='indicator',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
