# Generated by Django 5.0.2 on 2024-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_indicator_options_indicator_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if this is used for data recording'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_described',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if this is used for data descriptions and DQIs'),
        ),
    ]
