# Generated by Django 5.0.2 on 2024-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_activity_has_dqi_alter_activity_is_described'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['position'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
