# Generated by Django 5.0.2 on 2024-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_activity_options_activity_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadescription',
            options={'ordering': ['activity__position']},
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='emissions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of GHG emissions per kilogram (Kg of CO₂ equivalent)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='land_use',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of Land use per kilogram (m²)', max_digits=5, null=True),
        ),
    ]
