services:
  db:
    image: postgres:15.3
    container_name: foodflows_db
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: foodflows
  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    image: adminer:4.8.1
    depends_on: 
      - db
    ports:
      - 8080:8080
    container_name: foodflows_adminer
  web:
    build: .
    command: python3 foodflows/manage.py runserver 0.0.0.0:8989
    volumes:
      - .:/code
    ports:
      - 8989:8989
    depends_on:
      - db
    container_name: foodflows_web
